import streamlit as st
import json
import requests
import urllib.parse
from google import genai
from dotenv import load_dotenv
import os
import io
from gtts import gTTS

# Load environment variables
load_dotenv()

st.set_page_config(page_title="Visual Novel Engine", page_icon="📖", layout="wide")

st.markdown("""
<style>
.main { background: #1E1E1E; color: #FFF; }
.story-text { font-size: 1.2rem; line-height: 1.6; margin-top: 20px; margin-bottom: 20px; }
</style>
""", unsafe_allow_html=True)

st.title("📖 Visual Novel Engine")

# Phase 1: The Director's Cut (UI & Configuration)
@st.cache_resource
def get_gemini_client():
    return genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

client = get_gemini_client()

st.sidebar.title("🎬 Story Settings")
genre = st.sidebar.selectbox("Story Genre", ["Sci-Fi", "Fantasy", "Horror", "Cyberpunk", "Mystery", "Romance"])
art_style = st.sidebar.selectbox("Art Style", ["Realistic", "Anime", "Watercolor", "Oil Painting", "Pixel Art", "Comic Book"])

if st.sidebar.button("🗑️ Reset Adventure"):
    for key in list(st.session_state.keys()):
        del st.session_state[key]
    st.rerun()

# Initialize session state variables
if "history" not in st.session_state:
    st.session_state.history = []

if "current_scene" not in st.session_state:
    st.session_state.current_scene = None

# Phase 5: Graceful Failures for Media Generation
def generate_image(image_prompt, art_style):
    try:
        full_prompt = f"{image_prompt} in {art_style} style, highly detailed, masterpiece"
        encoded = urllib.parse.quote(full_prompt)
        url = f"https://image.pollinations.ai/prompt/{encoded}?width=800&height=400"
        res = requests.get(url, timeout=10)
        res.raise_for_status()
        return res.content
    except Exception as e:
        st.toast(f"Image server is busy, skipping visual... ({e})", icon="⚠️")
        return None

def generate_audio(text):
    try:
        tts = gTTS(text=text, lang='en')
        fp = io.BytesIO()
        tts.write_to_fp(fp)
        fp.seek(0)
        return fp.read()
    except Exception as e:
        st.toast(f"Audio server is busy, skipping narration... ({e})", icon="⚠️")
        return None

# Phase 2: The Structured JSON Engine (Prompting)
system_instruction = f"""
You are the narrator of a highly interactive {genre} visual novel.
Your responses MUST ALWAYS be a valid JSON object strictly matching this schema:
{{
  "story_text": "A detailed paragraph describing the current scene and narrative.",
  "image_prompt": "A heavily engineered prompt describing the visual scene to be generated by an AI image generator. Focus purely on visual descriptions. Do not include text in the image.",
  "options": ["Option 1 text", "Option 2 text", "Option 3 text"]
}}
Return ONLY the JSON string. Do not wrap it in markdown block quotes (no ```json).
"""

def generate_scene(user_input=None):
    with st.spinner("Generating next scene..."):
        prompt_content = user_input if user_input else f"Start the {genre} adventure."
        
        # Construct full prompt context
        full_prompt = system_instruction + "\n\nHistory:\n"
        for m in st.session_state.history:
            full_prompt += f"{m['role'].upper()}: {m['content']}\n"
        full_prompt += f"\nUSER: {prompt_content}\n\nReturn JSON ONLY."

        try:
            # Call Gemini
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=full_prompt
            )
            
            raw_text = response.text.strip()
            
            # Clean up potential markdown formatting just in case Gemini disobeys
            if raw_text.startswith("```json"):
                raw_text = raw_text[7:]
            elif raw_text.startswith("```"):
                raw_text = raw_text[3:]
            if raw_text.endswith("```"):
                raw_text = raw_text[:-3]
            raw_text = raw_text.strip()
            
            # Phase 2: JSON Parsing
            data = json.loads(raw_text)
            
            # Phase 4 & 5: Multi-Media Rendering & TTS with Graceful Failures
            img_bytes = generate_image(data["image_prompt"], art_style)
            audio_bytes = generate_audio(data["story_text"])
            
            # Save the parsed and fetched assets to session state
            scene = {
                "story_text": data["story_text"],
                "image_prompt": data["image_prompt"],
                "options": data.get("options", []),
                "image_bytes": img_bytes,
                "audio_bytes": audio_bytes
            }
            st.session_state.current_scene = scene
            
            # Update chat history
            if user_input:
                st.session_state.history.append({"role": "user", "content": user_input})
            st.session_state.history.append({"role": "assistant", "content": raw_text})
            
        except json.JSONDecodeError as e:
            st.error(f"Failed to parse AI response into JSON. The AI said: {raw_text}")
        except Exception as e:
            st.error(f"Failed to generate scene: {e}")


# Main UI Flow
if st.session_state.current_scene is None:
    st.info(f"Welcome to the Visual Novel Engine. Ready to explore a {genre} world?")
    if st.button("🚀 Start Adventure", type="primary", use_container_width=True):
        generate_scene()
        st.rerun()
else:
    scene = st.session_state.current_scene
    
    # Phase 4: Multi-Media Rendering
    if scene["image_bytes"]:
        st.image(scene["image_bytes"], use_container_width=True)
    
    st.markdown(f"<div class='story-text'>{scene['story_text']}</div>", unsafe_allow_html=True)
    
    if scene["audio_bytes"]:
        st.audio(scene["audio_bytes"], format="audio/mp3", autoplay=True)
        
    st.divider()
    st.subheader("What do you do next?")
    
    # Phase 3: Dynamic UI Generation
    # Using columns for options if possible, or vertical buttons
    for i, option in enumerate(scene["options"]):
        if st.button(option, key=f"btn_{i}", use_container_width=True):
            generate_scene(option)
            st.rerun()
